#+TITLE: Quiz User Manual 
#+AUTHOR: VLEAD
#+DATE: [2019-06-27 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document captures the instructions to include quiz
  sources(quiz template, quiz validator) as a library in the
  experiments.

* Steps to include Quiz in experiment
  *STEP 1 :* Clone the experiment  
  #+BEGIN_EXAMPLE 
  git clone http://github.com/virtual-labs/<<EXPERIMENT>>.git
  #+END_EXAMPLE

  *STEP 2 :* Change directory to experiment repo 
  #+BEGIN_EXAMPLE
  cd <<EXPERIMENT>>
  #+END_EXAMPLE

  *STEP 3 :* Get Quiz Library
  #+BEGIN_EXAMPLE
  make -k get-quiz-lib
  #+END_EXAMPLE
  This clones the =srip-quiz= repo in your experiment folder
  and then
  + Moves =quiz.html= template at lab and experiment
    level. This is a template where the quiz questions get
    rendered.
  + Moves =quiz-data.json= at lab and experiment level. This
    is a file where you include quiz questions along with
    the options and explanation in Json format.
  + Moves the quiz sources which are essential to validate
    the quiz and style the quiz template are moved to
    =src/quiz= folder.
  

  *STEP 4 :* Replace the questions in default quiz-data.json
  with the experiment related questions

  *STEP 5 :* Build the experiment to view the quiz
  #+BEGIN_EXAMPLE
  make -k build
  #+END_EXAMPLE

  *STEP 6 :* Run the experiment server
  #+BEGIN_EXAMPLE
  make -k run
  #+END_EXAMPLE
  
  *STEP 7 :* To view the experiment in the browser
  #+BEGIN_EXAMPLE
  http://localhost:8000/
  #+END_EXAMPLE
